const INT_CODES = {
    AIRLOCK000019: {0:"Normal",1:"No Data",2:"Missing  Data",3:"Extra Data"},
    AIRLOCK000020: {0:"Normal",1:"No Data",2:"Missing  Data",3:"Extra Data"},
    AIRLOCK000021: {0:"Normal",1:"No Data",2:"Missing  Data",3:"Extra Data"},
    AIRLOCK000022: {0:"Normal",1:"No Data",2:"Missing  Data",3:"Extra Data"},
    AIRLOCK000023: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000024: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000025: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000026: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000027: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000028: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000029: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000030: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000031: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000032: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000033: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000034: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000035: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000036: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000037: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000038: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000039: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000040: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000041: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000042: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000043: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000044: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000045: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000046: {0:"No History - a charge has not been initiated yet",1:"Presently charging",2:"Task completed normally",3:"Task terminated due to stop switch being toggled",4:"Task terminated due to an open circuit error",5:"Task terminated due to Wrong Batt or Hi-imp",6:"Task terminated due to an over-temperature error",7:"Amp-hour capacity test result OK",8:"Amp-hour capacity test error",9:"Task terminated due to low charge slope error",10:"Task terminated due to power error",11:"Task terminated due to reverse-polarity error",12:"Task terminated due to a short-circuit error",13:"Task terminated due to a time-out error",14:"Task terminated due to an external-temperature error",15:"Discharge",16:"Wait on Discharge",17:"Wait on Charge"},
    AIRLOCK000047: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    AIRLOCK000048: {0:"PUMP OFF CMD",1:"PUMP ON CMD"},
    AIRLOCK000050: {0:"CLOSED",1:"OPEN",2:"IN-TRANSIT",3:"FAILED"},
    AIRLOCK000051: {0:"CLOSED",1:"OPEN",2:"IN-TRANSIT",3:"FAILED"},
    AIRLOCK000052: {0:"CLOSED",1:"OPEN",2:"IN-TRANSIT",3:"FAILED"},
    AIRLOCK000053: {0:"RESET",1:"DRAIN",2:"DRYOUT",3:"EIB OFF",4:"OFF",5:"ON",6:"STARTUP",7:"TEST"},
    AIRLOCK000058: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    NODE1000001: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    NODE1000002: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    NODE2000003: {0:"RESET",1:"DRAIN",2:"DRYOUT",3:"EIB OFF",4:"OFF",5:"ON",6:"STARTUP",7:"TEST"},
    NODE2000004: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    NODE2000005: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    NODE3000004: {2:"STOP",4:"SHUTDOWN",8:"MAINTENANCE",16:"NORMAL",32:"STANDBY",64:"IDLE",128:"SYSTEM INITIALIZED"},
    NODE3000006: {1:"STOP",2:"SHUTDOWN",3:"STANDBY",4:"PROCESS",5:"HOT SERVICE",6:"FLUSH",7:"WARM SHUTDOWN"},
    NODE3000007: {0:"NONE",1:"VENT",2:"HEATUP",3:"PURGE",4:"FLOW",5:"TEST",6:"TEST_SV_1",7:"TEST_SV_2",8:"SERVICE"},
    NODE3000010: {1:"PROCESS",2:"STANDBY",3:"SHUTDOWN",4:"STOP",5:"VENT_DOME",6:"INERT_DOME",7:"FAST_SHUTDOWN",8:"N2_PURGE_SHUTDOWN"},
    NODE3000014: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    NODE3000015: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    NODE3000016: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    NODE3000018: {0:"RESET",1:"DRAIN",2:"DRYOUT",3:"EIB OFF",4:"OFF",5:"ON",6:"STARTUP",7:"TEST"},
    NODE3000020: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    P1000006: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    P1000007: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    P1000008: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    P1000009: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    P3000001: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    P3000002: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    P4000003: {0:"Not Enabled",1:"Enabled"},
    P4000006: {0:"Not Enabled",1:"Enabled"},
    P6000003: {0:"Not Enabled",1:"Enabled"},
    P6000006: {0:"Not Enabled",1:"Enabled"},
    RUSSEG000001: {1:"Crew Rescue",2:"Survival",3:"Reboost",4:"Proximity Operations",5:"EVA",6:"Microgravity",7:"Standard"},
    RUSSEG000002: {0:"Undetermined State",1:"SM KURS Equipment Set1 Operating"},
    RUSSEG000003: {0:"Undetermined State",1:"SM KURS Equipment Set2 Operating"},
    RUSSEG000004: {0:"Undetermined State",1:"SM KURS P1 P2 Failure"},
    RUSSEG000007: {0:"Undetermined State",1:"SM KURS-P Test Mode"},
    RUSSEG000008: {0:"Undetermined State",1:"SM KURS-P Capture Signal"},
    RUSSEG000009: {0:"Undetermined State",1:"SM KURS-P Target Acquisition Signal"},
    RUSSEG000010: {0:"Undetermined State",1:"SM KURS-P Functional Mode Signal"},
    RUSSEG000011: {0:"Undetermined State",1:"SM KURS-P In Standby Mode"},
    RUSSEG000012: {0:"Undetermined State",1:"SM Docking Flag"},
    //RUSSEG000013: {0:"SM UNDOCKED!!!",1:"SM Docked"},
    RUSSEG000013: {0:"Undetermined State",1:"SM Docked"},
    //RUSSEG000014: {0:"No vehicle docked",1:"Soyuz/Progress Docked"},
    RUSSEG000014: {0:"Undetermined State",1:"Soyuz/Progress Docked"},
    //RUSSEG000015: {0:"MLM Undocked!!!",1:"MLM Docked"},
    RUSSEG000015: {0:"Undetermined State",1:"MLM Docked"},
    //RUSSEG000016: {0:"MRM-1 Undocked!!!",1:"MRM-1 Docked"},
    RUSSEG000016: {0:"Undetermined State",1:"MRM-1 Docked"},
    //RUSSEG000017: {0:"No vehicle docked",1:"Soyuz/Progress Docked"},
    RUSSEG000017: {0:"Undetermined State",1:"Soyuz/Progress Docked"},
    //RUSSEG000018: {0:"No vehicle docked",1:"Soyuz/Progress Docked"},
    RUSSEG000018: {0:"Undetermined State",1:"Soyuz/Progress Docked"},
    //RUSSEG000019: {0:"No vehicle docked",1:"Soyuz/Progress Docked"},
    RUSSEG000019: {0:"No vehicle docked",1:"Soyuz/Progress Docked"},
    RUSSEG000020: {0:"Undetermined State",1:"Docked Vehicle Hooks Closed"},
    RUSSEG000021: {0:"Inertial Attitude",1:"LVLH SM",2:"Solar Orientation",3:"Current LVLH",4:"Current Inertial Attitude",5:"Damping",6:"TEA",7:"X-POP"},
    RUSSEG000022: {0:"Undetermined State",1:"SM SUDN Controls the Motion"},
    RUSSEG000023: {0:"Undetermined State",1:"SM SUDN Prepared to Free Drift Mode Transition"},
    RUSSEG000024: {0:"Pre-Starting Procedure Or Thruster Operation Readiness",1:"Thruster Operation Mode is Terminated"},
    RUSSEG000025: {0:"Reserv",1:"Thrusters",2:"Gyrodines",3:"Gyrodines with Desaturation on American Method",4:"Gyrodines with Desaturation on Russian Method",5:"Translational Thrusters Operating",6:"Thrusters help CMG (desaturate CMG)",7:"Free Drift Mode"},
    S0000006: {1:"STANDBY",2:"RESTART",3:"CHECKOUT",4:"DIRECTED_POSITION",5:"AUTOTRACK",6:"BLIND",7:"SHUTDOWN",8:"SWITCHOVER"},
    S0000007: {1:"STANDBY",2:"RESTART",3:"CHECKOUT",4:"DIRECTED_POSITION",5:"AUTOTRACK",6:"BLIND",7:"SHUTDOWN",8:"SWITCHOVER"},
    S0000008: {1:"STANDBY",2:"RESTART",3:"CHECKOUT",4:"DIRECTED_POSITION",5:"AUTOTRACK",6:"BLIND",7:"SHUTDOWN",8:"SWITCHOVER"},
    S0000009: {1:"STANDBY",2:"RESTART",3:"CHECKOUT",4:"DIRECTED_POSITION",5:"AUTOTRACK",6:"BLIND",7:"SHUTDOWN",8:"SWITCHOVER"},
    S0000010: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    S0000011: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    S0000012: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    S0000013: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    S1000006: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    S1000007: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    S1000008: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    S1000009: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    S3000001: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    S3000002: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    S4000003: {0:"Not Enabled",1:"Enabled"},
    S4000006: {0:"Not Enabled",1:"Enabled"},
    S6000003: {0:"Not Enabled",1:"Enabled"},
    S6000006: {0:"Not Enabled",1:"Enabled"},
    USLAB000001: {0:"NOT IN USE",1:"IN USE"},
    USLAB000002: {0:"NOT IN USE",1:"IN USE"},
    USLAB000003: {0:"NOT IN USE",1:"IN USE"},
    USLAB000004: {0:"NOT IN USE",1:"IN USE"},
    USLAB000011: {0:"ENABLED",1:"INHIBITED"},
    USLAB000012: {0:"Default",1:"WAIT",2:"RESERVED",3:"STANDBY",4:"CMG ATTITUDE CONTROL",5:"CMG/THRUSTER ASSIST ATTITUDE CONTROL",6:"USER DATA GENERATION",7:"FREEDRIFT"},
    USLAB000013: {0:"NONE",1:"GPS1",2:"GPS2",3:"Russian_Attitude",4:"Ku_Band"},
    USLAB000014: {0:"NONE",1:"RGA1",2:"RGA2",3:"RUSSIAN"},
    USLAB000015: {0:"NO_SOURCE",1:"Unused",2:"Unused",3:"RUSSIAN",4:"GPS1_DETERMINISTIC",5:"GPS2_DETERMINISTIC",6:"GROUND"},
    USLAB000016: {0:"ATTITUDE HOLD",1:"TEA"},
    USLAB000017: {0:"LVLH",1:"Inertial",2:"XPOP"},
    USLAB000041: {0:"FALSE",1:"TRUE"},
    USLAB000042: {0:"FALSE",1:"TRUE"},
    USLAB000043: {0:"DOING POSITION FIXES",1:"SV TIMING",2:"APPROXIMATE TIMING",3:"GPS TIME",4:"NEED INITIALIZATION",5:"GDOP NEEDED",6:"BAD TIMING",7:"NO USABLE SV",8:"ONLY 1 USABLE SVs",9:"ONLY 2 USABLE SVs",10:"ONLY 3 USABLE SVs",11:"BAD INTEGRITY",12:"NO VEL AVAIL",13:"UNUSABLE FIX"},
    USLAB000044: {0:"DOING POSITION FIXES",1:"SV TIMING",2:"APPROXIMATE TIMING",3:"GPS TIME",4:"NEED INITIALIZATION",5:"GDOP NEEDED",6:"BAD TIMING",7:"NO USABLE SV",8:"ONLY 1 USABLE SVs",9:"ONLY 2 USABLE SVs",10:"ONLY 3 USABLE SVs",11:"BAD INTEGRITY",12:"NO VEL AVAIL",13:"UNUSABLE FIX"},
    USLAB000062: {0:"FAIL",1:"OPEN",2:"CLSD",3:"TRNS"},
    USLAB000063: {0:"FAIL",1:"OPEN",2:"CLSD",3:"TRNS"},
    USLAB000064: {0:"RESET",1:"DRAIN",2:"DRYOUT",3:"EIB OFF",4:"OFF",5:"ON",6:"STARTUP",7:"TEST"},
    USLAB000065: {0:"RESET",1:"DRAIN",2:"DRYOUT",3:"EIB OFF",4:"OFF",5:"ON",6:"STARTUP",7:"TEST"},
    USLAB000066: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000067: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000068: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000069: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000070: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000071: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000072: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000073: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000074: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000075: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000076: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000077: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000078: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000079: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000080: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000081: {0:"FALSE",1:"TRUE"},
    USLAB000086: {1:"Standard",2:"Microgravity",4:"Reboost",8:"Proximity_Ops",16:"External_Ops",32:"Survival",64:"ASCR",127:"all_modes"},
    USLAB000088: {0:"INACTIVE",1:"ACTIVE"},
    USLAB000089: {0:"INACTIVE",1:"ACTIVE"},
    USLAB000090: {0:"INACTIVE",1:"ACTIVE"},
    USLAB000091: {0:"INACTIVE",1:"ACTIVE"},
    USLAB000092: {1:"String 1",2:"String 2"},
    USLAB000093: {0:"Backup",1:"Active"},
    USLAB000094: {0:"Backup",1:"Active"},
    USLAB000095: {0:" -",1:"WETA 113 (S3)",2:"S1 Upper Outboard (UPOB)",3:"SCU1 Mux",4:"S1 Lower Outboard (LOOB)",5:"JEM Channel 1",6:"JEM Channel 2",7:"S1 Upper Inboard (UPIB)",8:"S1 Lower Inboard (LOIB)",9:"Columbus 1",10:"Columbus 2",11:"P1 Upper Inboard (UPIB)",12:"SCU2 Mux",13:"Node 3 Starboard",14:"P1 Lower Inboard (LOIB)",15:"SCU1 Test",16:"WETA 112 (Node2)",17:"ORB1",18:"ORB2",19:"P1 Lower Outboard (LOOB)",20:"SCU2 Test",21:"P3 Aft",22:"Payload Rack",23:"VTR1",24:"VTR2",25:"Node 2 Nadir",26:"WETA 115 (Node1)",28:"Lab Starboard",31:"MBS POA Payload 3",32:"MBS POA",33:"SPDM S1",34:"SPDM S2",35:"MBS CLPA",36:"SPDM LEE",37:"MBS Mast",40:"SSRMS Base LEE",43:"SSRMS Base Elbow",48:"SSRMS Tip Elbow",50:"MSS Payload 3",51:"SSRMS Tip LEE",52:"Lab AVU1",53:"Lab AVU2",54:"Cup AVU1",55:"Cup AVU2",56:"SPDM OTCM 1",57:"SPDM Body 1",58:"SPDM OTCM 2",59:"SPDM Body 2",60:"SSRMS Payload 1",61:"SSRMS Payload 2",62:"SSRMS Payload 3",63:"MSS Payload 1",64:"MSS Payload 2",65:"Lab Rack 1D3",66:"Lab Rack 1P2",67:"Lab Rack 1P4",68:"Lab Camera",69:"Lab Rack 1O5",70:"Lab Rack 1O4",71:"Lab Rack 1O3",72:"Lab Rack 1O2",73:"Lab Rack 1O1",74:"Lab Rack 1S1",75:"Lab Rack 1S2",76:"Lab Rack 1S3",77:"Airlock Camera",78:"Lab Rack 1S4",79:"Node 1 Camera",80:"Node 3 Camera"},
    USLAB000096: {0:" -",1:"WETA 113 (S3)",2:"S1 Upper Outboard (UPOB)",3:"SCU1 Mux",4:"S1 Lower Outboard (LOOB)",5:"JEM Channel 1",6:"JEM Channel 2",7:"S1 Upper Inboard (UPIB)",8:"S1 Lower Inboard (LOIB)",9:"Columbus 1",10:"Columbus 2",11:"P1 Upper Inboard (UPIB)",12:"SCU2 Mux",13:"Node 3 Starboard",14:"P1 Lower Inboard (LOIB)",15:"SCU1 Test",16:"WETA 112 (Node2)",17:"ORB1",18:"ORB2",19:"P1 Lower Outboard (LOOB)",20:"SCU2 Test",21:"P3 Aft",22:"Payload Rack",23:"VTR1",24:"VTR2",25:"Node 2 Nadir",26:"WETA 115 (Node1)",28:"Lab Starboard",31:"MBS POA Payload 3",32:"MBS POA",33:"SPDM S1",34:"SPDM S2",35:"MBS CLPA",36:"SPDM LEE",37:"MBS Mast",40:"SSRMS Base LEE",43:"SSRMS Base Elbow",48:"SSRMS Tip Elbow",50:"MSS Payload 3",51:"SSRMS Tip LEE",52:"Lab AVU1",53:"Lab AVU2",54:"Cup AVU1",55:"Cup AVU2",56:"SPDM OTCM 1",57:"SPDM Body 1",58:"SPDM OTCM 2",59:"SPDM Body 2",60:"SSRMS Payload 1",61:"SSRMS Payload 2",62:"SSRMS Payload 3",63:"MSS Payload 1",64:"MSS Payload 2",65:"Lab Rack 1D3",66:"Lab Rack 1P2",67:"Lab Rack 1P4",68:"Lab Camera",69:"Lab Rack 1O5",70:"Lab Rack 1O4",71:"Lab Rack 1O3",72:"Lab Rack 1O2",73:"Lab Rack 1O1",74:"Lab Rack 1S1",75:"Lab Rack 1S2",76:"Lab Rack 1S3",77:"Airlock Camera",78:"Lab Rack 1S4",79:"Node 1 Camera",80:"Node 3 Camera"},
    USLAB000097: {0:" -",1:"WETA 113 (S3)",2:"S1 Upper Outboard (UPOB)",3:"SCU1 Mux",4:"S1 Lower Outboard (LOOB)",5:"JEM Channel 1",6:"JEM Channel 2",7:"S1 Upper Inboard (UPIB)",8:"S1 Lower Inboard (LOIB)",9:"Columbus 1",10:"Columbus 2",11:"P1 Upper Inboard (UPIB)",12:"SCU2 Mux",13:"Node 3 Starboard",14:"P1 Lower Inboard (LOIB)",15:"SCU1 Test",16:"WETA 112 (Node2)",17:"ORB1",18:"ORB2",19:"P1 Lower Outboard (LOOB)",20:"SCU2 Test",21:"P3 Aft",22:"Payload Rack",23:"VTR1",24:"VTR2",25:"Node 2 Nadir",26:"WETA 115 (Node1)",28:"Lab Starboard",31:"MBS POA Payload 3",32:"MBS POA",33:"SPDM S1",34:"SPDM S2",35:"MBS CLPA",36:"SPDM LEE",37:"MBS Mast",40:"SSRMS Base LEE",43:"SSRMS Base Elbow",48:"SSRMS Tip Elbow",50:"MSS Payload 3",51:"SSRMS Tip LEE",52:"Lab AVU1",53:"Lab AVU2",54:"Cup AVU1",55:"Cup AVU2",56:"SPDM OTCM 1",57:"SPDM Body 1",58:"SPDM OTCM 2",59:"SPDM Body 2",60:"SSRMS Payload 1",61:"SSRMS Payload 2",62:"SSRMS Payload 3",63:"MSS Payload 1",64:"MSS Payload 2",65:"Lab Rack 1D3",66:"Lab Rack 1P2",67:"Lab Rack 1P4",68:"Lab Camera",69:"Lab Rack 1O5",70:"Lab Rack 1O4",71:"Lab Rack 1O3",72:"Lab Rack 1O2",73:"Lab Rack 1O1",74:"Lab Rack 1S1",75:"Lab Rack 1S2",76:"Lab Rack 1S3",77:"Airlock Camera",78:"Lab Rack 1S4",79:"Node 1 Camera",80:"Node 3 Camera"},
    USLAB000098: {0:" -",1:"WETA 113 (S3)",2:"S1 Upper Outboard (UPOB)",3:"SCU1 Mux",4:"S1 Lower Outboard (LOOB)",5:"JEM Channel 1",6:"JEM Channel 2",7:"S1 Upper Inboard (UPIB)",8:"S1 Lower Inboard (LOIB)",9:"Columbus 1",10:"Columbus 2",11:"P1 Upper Inboard (UPIB)",12:"SCU2 Mux",13:"Node 3 Starboard",14:"P1 Lower Inboard (LOIB)",15:"SCU1 Test",16:"WETA 112 (Node2)",17:"ORB1",18:"ORB2",19:"P1 Lower Outboard (LOOB)",20:"SCU2 Test",21:"P3 Aft",22:"Payload Rack",23:"VTR1",24:"VTR2",25:"Node 2 Nadir",26:"WETA 115 (Node1)",28:"Lab Starboard",31:"MBS POA Payload 3",32:"MBS POA",33:"SPDM S1",34:"SPDM S2",35:"MBS CLPA",36:"SPDM LEE",37:"MBS Mast",40:"SSRMS Base LEE",43:"SSRMS Base Elbow",48:"SSRMS Tip Elbow",50:"MSS Payload 3",51:"SSRMS Tip LEE",52:"Lab AVU1",53:"Lab AVU2",54:"Cup AVU1",55:"Cup AVU2",56:"SPDM OTCM 1",57:"SPDM Body 1",58:"SPDM OTCM 2",59:"SPDM Body 2",60:"SSRMS Payload 1",61:"SSRMS Payload 2",62:"SSRMS Payload 3",63:"MSS Payload 1",64:"MSS Payload 2",65:"Lab Rack 1D3",66:"Lab Rack 1P2",67:"Lab Rack 1P4",68:"Lab Camera",69:"Lab Rack 1O5",70:"Lab Rack 1O4",71:"Lab Rack 1O3",72:"Lab Rack 1O2",73:"Lab Rack 1O1",74:"Lab Rack 1S1",75:"Lab Rack 1S2",76:"Lab Rack 1S3",77:"Airlock Camera",78:"Lab Rack 1S4",79:"Node 1 Camera",80:"Node 3 Camera"},
    USLAB000099: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000100: {0:"Off-Ok",1:"Not-Off Ok",3:"Not-Off Failed"},
    USLAB000101: {0:"Frame Sync unlocked",1:"Frame Sync locked"},
    Z1000013: {0:"RESET",1:"NORMAL"},
    CSAMT000002: {0:"Translating", 1:"WS1 ", 2:"WS2 ", 3:"WS3 ", 4:"WS4 ", 5:"WS5 ", 6:"WS6 ",7:"WS7 ",8:"WS8"},
    CSASSRMS002: {1:"Lab ", 2:"Node3 ", 4:"Node2 ", 7:"MBS PDGF 1 ", 8:"MBS PDGF 2 ", 11:"MBS PDGF 3 ", 13:"MBS PDGF 4 ", 14:"FGB ", 16:"POA ", 19:"SSRMS Tip LEE ", 63:"Undefined"},
    CSASSRMS003: {0:"LEE A ", 5:"LEE B"},
    CSASSRMS011: {0:"Released",1:"Captive",2:"Captured"},
    CSASPDM0002: {1:"Lab ", 2:"Node3 ", 4:"Node2 ", 7:"MBS PDGF 1 ", 8:"MBS PDGF 2 ", 11:"MBS PDGF 3 ", 13:"MBS PDGF 4 ", 14:"FGB ", 16:"POA ", 19:"SSRMS Tip LEE ", 63:"Undefined"},
    CSASPDM0010: {0:"Released",1:"Captive",2:"Captured"},
    CSASPDM0019: {0:"Released",1:"Captive",2:"Captured"},
    CSASPDM0022: {0:"Released",1:"Captive",2:"Captured"},
    CSAMBS00002: {0:"Released",1:"Captured"},
    CSAMBA00004: {0:"Released",1:"Captive",2:"Captured"},
};